create_ip -name hbm -vendor xilinx.com -library ip -version 1.0 -module_name hbm_ram
set_property -dict [list \
  CONFIG.USER_APB_EN {false} \
  CONFIG.USER_AUTO_POPULATE {yes} \
  CONFIG.USER_AXI_CLK_FREQ {400} \
  CONFIG.USER_EXAMPLE_TG {SYNTHESIZABLE} \
  CONFIG.USER_HBM_TCK_0 {800} \
  CONFIG.USER_MC0_BG_INTERLEAVE_EN {false} \
  CONFIG.USER_MC0_DQ_PARITY_EN {true} \
  CONFIG.USER_MC0_EN_DATA_MASK {true} \
  CONFIG.USER_MC0_MANUAL_ADDR_MAP_SEL {false} \
  CONFIG.USER_MC0_TEMP_CTRL_SELF_REF_INTVL {true} \
  CONFIG.USER_MC0_TRAFFIC_OPTION {Linear} \
  CONFIG.USER_MC_ENABLE_02 {FALSE} \
  CONFIG.USER_MC_ENABLE_03 {FALSE} \
  CONFIG.USER_MC_ENABLE_04 {FALSE} \
  CONFIG.USER_MC_ENABLE_05 {FALSE} \
  CONFIG.USER_MC_ENABLE_06 {FALSE} \
  CONFIG.USER_MC_ENABLE_07 {FALSE} \
  CONFIG.USER_SAXI_14 {false} \
  CONFIG.USER_SAXI_15 {false} \
  CONFIG.USER_SWITCH_ENABLE_00 {FALSE} \
  CONFIG.USER_XSDB_INTF_EN {FALSE} \
] [get_ips hbm_ram]