set pll [create_ip -name clk_wiz -vendor xilinx.com -library ip -module_name pll]

# User Parameters
set_property -dict [list \
  CONFIG.AUTO_PRIMITIVE {PLL} \
  CONFIG.CLKOUT1_DRIVES {Buffer} \
  CONFIG.CLKOUT1_JITTER {229.362} \
  CONFIG.CLKOUT1_PHASE_ERROR {114.212} \
  CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {10.000} \
  CONFIG.CLKOUT2_DRIVES {Buffer} \
  CONFIG.CLKOUT2_JITTER {200.312} \
  CONFIG.CLKOUT2_PHASE_ERROR {114.212} \
  CONFIG.CLKOUT2_REQUESTED_OUT_FREQ {20.000} \
  CONFIG.CLKOUT2_USED {true} \
  CONFIG.CLKOUT3_DRIVES {Buffer} \
  CONFIG.CLKOUT4_DRIVES {Buffer} \
  CONFIG.CLKOUT5_DRIVES {Buffer} \
  CONFIG.CLKOUT6_DRIVES {Buffer} \
  CONFIG.CLKOUT7_DRIVES {Buffer} \
  CONFIG.CLK_OUT1_PORT {clk_out100} \
  CONFIG.CLK_OUT2_PORT {clk_out200} \
  CONFIG.FEEDBACK_SOURCE {FDBK_AUTO} \
  CONFIG.MMCM_BANDWIDTH {OPTIMIZED} \
  CONFIG.MMCM_CLKFBOUT_MULT_F {8} \
  CONFIG.MMCM_CLKOUT0_DIVIDE_F {80} \
  CONFIG.MMCM_CLKOUT1_DIVIDE {40} \
  CONFIG.MMCM_COMPENSATION {AUTO} \
  CONFIG.NUM_OUT_CLKS {2} \
  CONFIG.OPTIMIZE_CLOCKING_STRUCTURE_EN {true} \
  CONFIG.PRIMITIVE {Auto} \
  CONFIG.PRIM_SOURCE {Differential_clock_capable_pin} \
  CONFIG.RESET_PORT {resetn} \
  CONFIG.RESET_TYPE {ACTIVE_LOW} \
  CONFIG.USE_LOCKED {true} \
  CONFIG.USE_RESET {true} \
] [get_ips pll]